#!/usr/bin/env python3
#=========================================================================
# verif_gen_elf_tests.py
#=========================================================================
# Generates per-suite ELF test .v files for ZeppelinV8 and Zeppelin.
#
# Suite configurations are loaded from a YAML file (default:
# verif_elf_test_suites.yml in the same directory as this script).
#
# Usage:
#   # Generate .v files from the config YAML (default)
#   python tools/verif_gen_elf_tests.py
#
#   # Generate .v files from a specific config
#   python tools/verif_gen_elf_tests.py --config tools/verif_elf_test_suites.yml
#
#   # (Re)generate the YAML by parsing the existing _test_suites.vh files
#   python tools/verif_gen_elf_tests.py --refer
#   python tools/verif_gen_elf_tests.py --refer --config out.yml
#
#   # Preview what would be written without writing
#   python tools/verif_gen_elf_tests.py --dry-run

import argparse
import re
import sys
from pathlib import Path

import yaml

#-------------------------------------------------------------------------
# Paths
#-------------------------------------------------------------------------

SCRIPT_DIR   = Path(__file__).resolve().parent
REPO_ROOT    = SCRIPT_DIR.parent
DEFAULT_CONFIG = SCRIPT_DIR / "verif_elf_test_suites.yml"

#-------------------------------------------------------------------------
# .v file template
#-------------------------------------------------------------------------

_V_TEMPLATE = """\
//========================================================================
// {module_name}.v
//========================================================================
// ELF test suite {suite_num}: {comment}
// Auto-generated by tools/verif_gen_elf_tests.py -- do not edit by hand.

`include "{harness_include}"

module {module_name};
  {version}TestHarness{param_block} h();

  string elf_file;

  initial begin
    test_bench_begin( `__FILE__ );

    h.t.timeout = 1000000;
    if ( !$value$plusargs( "elf=%s", elf_file ) )
      $fatal( 0, "No ELF file specified with +elf=/path/to/elf" );

    h.t.test_case_begin( $sformatf( "suite {suite_num}: %s", elf_file ) );
    h.load_elf( elf_file );
    h.check_traces();
    h.t.test_case_end();

    test_bench_end();
  end
endmodule
"""

#=========================================================================
# VH parser (used by --refer)
#=========================================================================

def _parse_value( s ):
  """Convert a Verilog parameter value string to a Python int or str."""
  s = s.strip()
  try:
    return int(s)
  except ValueError:
    pass
  if s.startswith(("0x", "0X")):
    try:
      return int(s, 16)
    except ValueError:
      pass
  # Verilog bit-vector, expression, or identifier — keep as string
  return s


def parse_vh( vh_path ):
  """Parse a _test_suites.vh file and return a list of suite dicts.

  Each dict has keys: num (int), category (str), comment (str),
  params (dict of non-suite_num overrides).
  """
  text = vh_path.read_text()
  suites      = []
  category    = ""

  # Category / section header patterns (VH uses both styles)
  cat_re  = re.compile(
    r'//[=\-]{6,}\n\s*//\s*(Category\s+\w+:\s*.+?)\s*\n',
    re.MULTILINE,
  )
  sec_re  = re.compile(
    r'//[-]{6,}\n\s*//\s*([^/\n][^\n]*?)\s*\n\s*//[-]{6,}',
    re.MULTILINE,
  )

  # Suite block: "// Suite N: comment\n  `MODULE #(\n  params\n  ) suite_N();"
  # [^\n]+ captures only the first comment line; (?:\s*//[^\n]*\n)* skips
  # any continuation comment lines before the SUITE_MODULE instantiation.
  suite_re = re.compile(
    r'//\s*Suite\s+(\d+):\s*([^\n]+)\n'
    r'(?:\s*//[^\n]*\n)*'
    r'\s*`\w+_SUITE_MODULE\s*#\s*\(\s*\n'
    r'(.*?)'
    r'\s*\)\s*suite_\d+\s*\(\s*\)',
    re.DOTALL,
  )

  # Build a sorted list of (position, category_name) from both header styles
  cat_positions = []
  for m in cat_re.finditer(text):
    cat_positions.append((m.start(), m.group(1).strip()))
  for m in sec_re.finditer(text):
    name = m.group(1).strip()
    # Skip VH-internal comment blocks (guard header, etc.)
    if len(name) < 60 and not name.startswith("//"):
      cat_positions.append((m.start(), name))
  cat_positions.sort()

  for m in suite_re.finditer(text):
    suite_num   = int(m.group(1))
    comment     = m.group(2).strip()
    params_text = m.group(3)

    # Nearest category that precedes this suite block
    pos = m.start()
    for cpos, cname in reversed(cat_positions):
      if cpos < pos:
        category = cname
        break

    # Parse parameter overrides (skip p_suite_num, skip expressions)
    params = {}
    for pm in re.finditer(r'\.\s*(p_\w+)\s*\(([^)]+)\)', params_text):
      name = pm.group(1)
      if name == "p_suite_num":
        continue
      params[name] = _parse_value(pm.group(2))

    suites.append({
      "num":      suite_num,
      "category": category,
      "comment":  comment,
      "params":   params,
    })

  return suites

#=========================================================================
# --refer: generate YAML from VH files
#=========================================================================

_VERSION_META = {
  "Zeppelin": {
    "harness_include": "hw/top/test/ZeppelinTestHarness.v",
    "output_dir":      "hw/top/test/riscv_dv_asm/elf_suites",
    "vh_source":       "hw/top/test/Zeppelin_test/Zeppelin_test_suites.vh",
  },
  "ZeppelinV8": {
    "harness_include": "hw/top/test/ZeppelinV8TestHarness.v",
    "output_dir":      "hw/top/test/riscv_dv_asm/elf_suites",
    "vh_source":       "hw/top/test/ZeppelinV8_test/ZeppelinV8_test_suites.vh",
  },
}

_CMAKE_FILENAME = "riscv_dv_elf_suites.cmake"

def cmd_refer( config_path ):
  """Parse existing _test_suites.vh files and write a reference YAML."""
  versions = {}
  for version, meta in _VERSION_META.items():
    vh_path = REPO_ROOT / meta["vh_source"]
    if not vh_path.exists():
      print(f"  WARNING: VH not found, skipping {version}: {vh_path}")
      continue
    suites = parse_vh(vh_path)
    print(f"  {version}: parsed {len(suites)} suite(s) from {vh_path.name}")
    versions[version] = {
      "harness_include": meta["harness_include"],
      "output_dir":      meta["output_dir"],
      "vh_source":       meta["vh_source"],
      "suites":          suites,
    }

  config_path.parent.mkdir(parents=True, exist_ok=True)
  with config_path.open("w") as f:
    f.write(
      "# ELF test suite configurations\n"
      "# Generated by: python tools/verif_gen_elf_tests.py --refer\n"
      "# Edit this file and re-run verif_gen_elf_tests.py to regenerate .v files.\n"
      "# Each suite produces one binary that runs a single ELF through\n"
      "# the specified harness configuration.\n\n"
    )
    yaml.dump({"versions": versions}, f,
              default_flow_style=False, sort_keys=False, allow_unicode=True)

  print(f"\n  Written: {config_path}")

#=========================================================================
# .v file generation
#=========================================================================

# Params whose width is p_num_pipes*8 bits (one byte per pipe)
_PER_PIPE_PARAMS    = {"p_sim_d2x_bp", "p_sim_x2w_bp"}
# Params whose width is p_num_fe_lanes*8 bits (one byte per lane)
_PER_FE_LANE_PARAMS = {"p_sim_f2d_bp"}

# Matches a concatenation of 8-bit Verilog literals: {8'd0, 8'd5, ...}
_BYTE_CONCAT_RE = re.compile(r"^\{((?:8'd\d+,\s*)*8'd\d+)\}$")


def _zero_pad_concat( value, target_bytes ):
  """Prepend 8'd0 terms to a {8'd..., ...} concat to reach target_bytes."""
  m = _BYTE_CONCAT_RE.match(str(value).replace(" ", ""))
  if not m:
    return value
  terms = [t.strip() for t in m.group(1).split(",")]
  if len(terms) >= target_bytes:
    return value
  pad = ["8'd0"] * (target_bytes - len(terms))
  return "{" + ", ".join(pad + terms) + "}"


def _format_harness_params( params ):
  """
  Return a ' #(\\n    .p_x (v)\\n  )' block for the harness instantiation,
  or an empty string when there are no overrides.
  """
  if not params:
    return ""

  # Compute expected byte counts for variable-width backpressure params
  num_alus     = int(params.get("p_num_alus",     4))
  num_muls     = int(params.get("p_num_muls",     2))
  num_pipes    = int(params.get("p_num_pipes",    num_alus + num_muls + 2))
  num_fe_lanes = int(params.get("p_num_fe_lanes", 4))

  max_name_len = max(len(name) for name in params)
  lines = []
  for name, value in params.items():
    if name in _PER_PIPE_PARAMS:
      value = _zero_pad_concat(value, num_pipes)
    elif name in _PER_FE_LANE_PARAMS:
      value = _zero_pad_concat(value, num_fe_lanes)
    padding = " " * (max_name_len - len(name))
    lines.append(f"    .{name}{padding} ({value})")

  return " #(\n" + ",\n".join(lines) + "\n  )"


def _generate_v( version, meta, suite ):
  """
  Return the .v file content string for one suite.
  """
  module_name = f"{version}_elf_test_suite_{suite['num']}"
  param_block = _format_harness_params(suite.get("params") or {})

  return _V_TEMPLATE.format(
    module_name     = module_name,
    version         = version,
    suite_num       = suite["num"],
    comment         = suite.get("comment", ""),
    harness_include = meta["harness_include"],
    param_block     = param_block,
  )


def _write_cmake( output_dir, rel_paths, dry_run=False ):
  """Write riscv_dv_elf_suites.cmake listing all generated .v files."""
  cmake_path = output_dir / _CMAKE_FILENAME
  lines      = [
    f"# {_CMAKE_FILENAME}\n",
    "# Auto-generated by tools/verif_gen_elf_tests.py -- do not edit by hand.\n\n",
    "set(ELF_SUITE_FILES\n",
  ]
  for p in rel_paths:
    lines.append(f"  {p}\n")
  lines.append(")\n")
  content = "".join(lines)

  if dry_run:
    print(f"    [dry-run] would write {cmake_path.name}")
    return

  if cmake_path.exists() and cmake_path.read_text() == content:
    print(f"    unchanged  {cmake_path.name}")
    return

  cmake_path.write_text(content)
  print(f"    wrote      {cmake_path.name}")


def cmd_clean( config_path, dry_run=False ):
  """Delete all generated ELF test .v files and the cmake manifest."""
  if not config_path.exists():
    print(f"Error: config not found: {config_path}", file=sys.stderr)
    print("  Run with --refer to generate it from the VH files.", file=sys.stderr)
    sys.exit(1)

  with config_path.open() as f:
    config = yaml.safe_load(f)

  versions      = config.get("versions", {})
  total_deleted = 0
  total_missing = 0
  seen_dirs     = set()

  for version, meta in versions.items():
    suites     = meta.get("suites", [])
    output_dir = REPO_ROOT / meta["output_dir"]
    print(f"\n  {version}: {len(suites)} suite(s) in {output_dir}")

    for suite in suites:
      module_name = f"{version}_elf_test_suite_{suite['num']}"
      target      = output_dir / f"{module_name}.v"

      if dry_run:
        status = "would delete" if target.exists() else "not found   "
        print(f"    [dry-run] {status}  {target.name}")
        if target.exists():
          total_deleted += 1
        continue

      if target.exists():
        target.unlink()
        print(f"    deleted  {target.name}")
        total_deleted += 1
      else:
        print(f"    missing  {target.name}")
        total_missing += 1

    seen_dirs.add(output_dir)

  # Remove cmake manifest from each output directory
  for output_dir in seen_dirs:
    cmake_path = output_dir / _CMAKE_FILENAME
    if dry_run:
      status = "would delete" if cmake_path.exists() else "not found   "
      print(f"\n    [dry-run] {status}  {cmake_path.name}")
      if cmake_path.exists():
        total_deleted += 1
    elif cmake_path.exists():
      cmake_path.unlink()
      print(f"\n    deleted  {cmake_path.name}")
      total_deleted += 1

  if dry_run:
    print(f"\n  Would delete {total_deleted} file(s).")
  else:
    print(f"\n  Deleted {total_deleted} file(s), {total_missing} already missing.")


def cmd_generate( config_path, dry_run=False ):
  """Load config YAML and write .v files and the cmake manifest for every suite."""
  if not config_path.exists():
    print(f"Error: config not found: {config_path}", file=sys.stderr)
    print("  Run with --refer to generate it from the VH files.", file=sys.stderr)
    sys.exit(1)

  with config_path.open() as f:
    config = yaml.safe_load(f)

  versions       = config.get("versions", {})
  total_written  = 0
  total_skipped  = 0
  all_rel_paths  = []   # collects paths for the cmake manifest
  output_dirs    = set()

  for version, meta in versions.items():
    suites     = meta.get("suites", [])
    output_dir = REPO_ROOT / meta["output_dir"]
    print(f"\n  {version}: {len(suites)} suite(s) → {output_dir}")

    if not dry_run:
      output_dir.mkdir(parents=True, exist_ok=True)
    output_dirs.add(output_dir)

    for suite in suites:
      module_name = f"{version}_elf_test_suite_{suite['num']}"
      out_path    = output_dir / f"{module_name}.v"
      rel_path    = f"{meta['output_dir']}/{module_name}.v"
      content     = _generate_v(version, meta, suite)
      all_rel_paths.append(rel_path)

      if dry_run:
        print(f"    [dry-run] would write {out_path.name}")
        total_skipped += 1
        continue

      # Skip if content is unchanged (avoids touching mtime)
      if out_path.exists() and out_path.read_text() == content:
        print(f"    unchanged  {out_path.name}")
        total_skipped += 1
        continue

      out_path.write_text(content)
      print(f"    wrote      {out_path.name}")
      total_written += 1

  # Write cmake manifest (one per unique output directory)
  for output_dir in output_dirs:
    print(f"\n  cmake manifest → {output_dir}")
    _write_cmake(output_dir, all_rel_paths, dry_run=dry_run)

  print(f"\n  Wrote {total_written} file(s), skipped {total_skipped} unchanged.")

#=========================================================================
# main
#=========================================================================

def main():
  parser = argparse.ArgumentParser(
    description="Generate per-suite ELF test .v files for ZeppelinV8 and Zeppelin."
  )
  parser.add_argument(
    "--config", type=Path, default=DEFAULT_CONFIG,
    metavar="PATH",
    help=f"Suite configuration YAML (default: {DEFAULT_CONFIG.name})",
  )
  parser.add_argument(
    "--refer", action="store_true",
    help="(Re)generate the config YAML by parsing the existing _test_suites.vh files.",
  )
  parser.add_argument(
    "--dry-run", action="store_true",
    help="Print what would be written/deleted without touching any files.",
  )
  parser.add_argument(
    "--clean", action="store_true",
    help="Delete all generated ELF test .v files listed in the config YAML.",
  )
  args = parser.parse_args()

  _banner = lambda msg: print(f"\n{'=' * 72}\n  {msg}\n{'=' * 72}")

  if args.refer:
    _banner("Generating reference YAML from VH files")
    cmd_refer(args.config)
  elif args.clean:
    _banner(f"Cleaning ELF test .v files from {args.config.name}")
    cmd_clean(args.config, dry_run=args.dry_run)
  else:
    _banner(f"Generating ELF test .v files from {args.config.name}")
    cmd_generate(args.config, dry_run=args.dry_run)


if __name__ == "__main__":
  main()
